language: ruby

rvm:
  - ree-1.8.7
  - 1.8.7
  - 1.9.2
  - 1.9.3

branches:
  only:
    - 2.0.0.rc1

notifications:
  irc:
    - "irc.freenode.org#cucumber-chef"

before_script:
  - mkdir -p $HOME/.chef/

# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
