language: ruby

rvm:
  - 1.9.2
  - 1.9.3

before_install:
  - sudo apt-get -qq update

before_script:
  - mkdir -p $HOME/.chef/

bundler_args: --binstubs

script: "rake spec"

notifications:
  irc: "irc.freenode.net#jovelabs"
